/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type AlienPassportFeedback = {
  _id: string;
  _type: 'alienPassportFeedback';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  gemeente: string;
  complaint: string;
  contact?: string;
  submittedAt: string;
};

export type Vacancy = {
  _id: string;
  _type: 'vacancy';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocaleString;
  id: Slug;
  description: LocaleText;
  tasks: Array<{
    title: LocaleString;
    description: LocaleText;
    _key: string;
  }>;
};

export type LocaleText = {
  _type: 'localeText';
  be?: string;
  nl?: string;
};

export type LocaleString = {
  _type: 'localeString';
  be?: string;
  nl?: string;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Feedback = {
  _id: string;
  _type: 'feedback';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  text: LocaleText;
  signature: LocaleString;
};

export type Guide = {
  _id: string;
  _type: 'guide';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: Slug;
  title: LocaleString;
  excerpt?: LocaleText;
  content: LocaleContent;
  featured: boolean;
  publishedAt: string;
};

export type LocaleContent = {
  _type: 'localeContent';
  be?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  nl?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type News = {
  _id: string;
  _type: 'news';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: Slug;
  title: LocaleString;
  description: LocaleText;
  backgroundUrl: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  content: LocaleContent;
  featuredMain: boolean;
  featured: boolean;
  publishingDate: string;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Event = {
  _id: string;
  _type: 'event';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: Slug;
  title: LocaleString;
  description: LocaleText;
  backgroundUrl: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  content: LocaleContent;
  timeframe: Timeframe;
  rescheduled?: boolean;
  cancelled?: boolean;
  rescheduledTimeframe?: Timeframe;
  location: string;
  ticketsLink?: string;
  ticketsLabel?: LocaleString;
  tipsLink?: string;
  tipsLabel?: LocaleString;
  successText?: LocaleString;
  gtmEventValue?: string;
};

export type Timeframe = {
  _type: 'timeframe';
  start: string;
  end: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AlienPassportFeedback
  | Vacancy
  | LocaleText
  | LocaleString
  | Slug
  | Feedback
  | Guide
  | LocaleContent
  | SanityImageAssetReference
  | News
  | SanityImageCrop
  | SanityImageHotspot
  | Event
  | Timeframe
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;
